smrtcells_targets:
  - alignment
  - stats  # req: alignment
  - coverage  # req: alignment
  - coverage_qc  # req: alignment
  - kmers

sample_targets:
  - pbsv_vcf  # req: alignment in config['smrtcells_targets']
  - deepvariant  # req: alignment in config['smrtcells_targets']
  - whatshap  # req: deepvariant
  - coverage  # req: whatshap
  - kmers  # req: kmers in config['smrtcells_targets']
  - assembly
  - tandem-genotypes  # req: whatshap

cohort_targets:
  - pbsv_vcf  # req: pbsv_vcf in config['sample_targets']
  - svpack  # req: pbsv_vcf in config['sample_targets']
  - deepvariant_vcf  # req: deepvariant, whatshap in config['sample_targets']
  - slivar  # req: deepvariant, whatshap in config['sample_targets']
  - trio_assembly

# temporary storage
tmpdir: '/tmp'

# jellyfish and genomescope
kmer_length: 21

# deepvariant
#DEEPVARIANT_VERSION: '1.3.0'  # CPU-only, will require modifying threads for call_variants rules
DEEPVARIANT_VERSION: '1.3.0-gpu'  # GPU
N_SHARDS: 256

# glnexus
GLNEXUS_VERSION: 'v1.4.1'

# last/tandem-genotypes
score_matrix: 'resources/tandem-genotypes/score_matrix.par'

# slivar
slivar_js: 'resources/slivar/slivar-functions.js'
# slivar filters
# gnomad -> frequency in gnomAD v3
# hprc -> frequency in 40 HPRC samples sequenced with HiFi
# af -> allele frequency
# nhomalt -> number of samples with homalt genotype
# gq -> genotype quality as output by DeepVariant or GLnexus
max_gnomad_af: 0.01  # for all variants
max_hprc_af: 0.01  # for all variants
max_gnomad_nhomalt: 4  # for all variants
max_hprc_nhomalt: 4  # for all variants
max_gnomad_ac: 4  # for 'dominant' variants
max_hprc_ac: 4  # for 'dominant' variants
min_gq: 5

# lookups for slivar tsv annotations
lof_lookup_url: 'https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz'
lof_lookup: 'resources/slivar/lof_lookup.txt'
clinvar_lookup_url: 'ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/gene_condition_source_id'
clinvar_lookup: 'resources/slivar/clinvar_gene_desc.txt'

# cohorts yaml
cohort_yaml: 'cohort.yaml'

# lookups for gene mapping
ensembl_to_hgnc: 'resources/hpo/ensembl.hgncSymbol.tsv'

# lookups for HPO annotations
hpo:
  terms: 'resources/hpo/hpoTerms.txt'
  dag: 'resources/hpo/hpoDag.txt'
  annotations: 'resources/hpo/ensembl.hpoPhenotype.tsv'